name: Automatic Merge

on:
    check_run:
      types:
        - completed

jobs:
    automerge:
      name: Automatic Merge on Conditions
      runs-on: ubuntu-latest  
      permissions:
        contents: write
        pull-requests: write
      
      steps:
        - name: Check Required Labels
          uses: yogevbd/enforce-label-action@2.1.0
          with:
            REQUIRED_LABELS_ALL: "lgtm"

        - id: automerge-lgtm
          name: Automerge with main
          uses: "pascalgn/automerge-action@v0.16.4"
          env:
            GITHUB_TOKEN: "${{ github.token }}"
            MERGE_LABELS: "lgtm"
            MERGE_METHOD: "squash"