name: Automerge

on:
    pull_request:
        types:
        - labeled
        - unlabeled
        - synchronize
        - opened
        - edited
        - ready_for_review
        - reopened
        - unlocked
    # pull_request_review:
    #     types:
    #     - submitted
    # check_suite:
    #     types:
    #     - completed
    status: {}

jobs:
  check-release-gates:
      name: Check LGTM Gate
      runs-on: ubuntu-latest

      steps:
        - name: Enforce Gates
          uses: yogevbd/enforce-label-action@2.1.0
          with:
            REQUIRED_LABELS_ALL: "lgtm"

  automerge:
    name: Automerge Job
    runs-on: ubuntu-latest
    needs: check-release-gates
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - id: auto-merge
      name: Merge with Target Branch
      uses: pascalgn/automerge-action@v0.16.3
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "lgtm"
          MERGE_METHOD: "squash"
          MERGE_ERROR_FAIL: true


    #   - id: dry-run
    #     name: Automerge Dry Run
    #     uses: reitermarkus/automerge@v2
    #     with:
    #       token: ${{ secrets.GITHUB_TOKEN }}
    #       merge-method: squash
    #       do-not-merge-labels: never-merge
    #       required-labels: lgtm
    #       pull-request: ${{ github.event.inputs.pull-request }}
    #       review: ${{ github.event.inputs.review }}
    #       dry-run: true

    #   - id: auto-merge
    #     name: Merge with Target Branch
    #     uses: reitermarkus/automerge@v2
    #     with:
    #         token: ${{ secrets.GITHUB_TOKEN }}
    #         merge-method: squash
    #         do-not-merge-labels: never-merge
    #         required-labels: lgtm
    #         pull-request: ${{ github.event.inputs.pull-request }}
    #         review: ${{ github.event.inputs.review }}
