name: Merge and Cleanup

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
    housekeeping:
      name: Housekeeping
      runs-on: ubuntu-latest
      if: >
        contains(github.event.pull_request.labels.*.name, 'lgtm')  
      permissions:
        contents: write
        pull-requests: write
      
      steps:
        - name: Check Required Labels
          uses: yogevbd/enforce-label-action@2.1.0
          with:
            REQUIRED_LABELS_ALL: "lgtm"

        - name: Checkout
          uses: actions/checkout@v4

        - name: Install and Build
          env: 
            REACT_APP_DOCUSAURUS_BASE_URL: ${{ vars.DOCUSAURUS_BASE_URL }}pr-${{ github.event.pull_request.number }}
          run: |
            npm install
            npm run build

        - name: Remove Ephemeral Artifacts
          uses: rossjrw/pr-preview-action@v1
          with:
            source-dir: ./build/
            action: remove

        - id: automerge-lgtm
          name: Automerge with main
          uses: "pascalgn/automerge-action@v0.16.4"
          env:
            GITHUB_TOKEN: "${{ github.token }}"
            MERGE_LABELS: "lgtm"
            MERGE_METHOD: "squash"
            MERGE_ERROR_FAIL: true