name: Automatic Merge

on:
    pull_request:
      types: 
        - labeled
        - unlabeled
        - synchronize
        - opened
        - edited
        - ready_for_review
        - reopened
        - unlocked
    pull_request_review:
      types:
        - submitted
    check_suite:
      types:
        - completed

jobs:
    automerge:
      name: Automatic Merge on Conditions
      runs-on: ubuntu-latest  
      if: >
        contains(github.event.pull_request.labels.*.name, 'lgtm')
      permissions:
        contents: write
        pull-requests: write
      
      steps:
        - id: automerge-lgtm
          name: Automerge with main
          uses: "pascalgn/automerge-action@v0.16.4"
          env:
            GITHUB_TOKEN: "${{ github.token }}"
            MERGE_LABELS: "lgtm"
            MERGE_METHOD: "squash"