name: automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: >
        contains(github.event.pull_request.labels.*.name, 'lgtm')
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enforce LGTM Gate
        uses: yogevbd/enforce-label-action@2.1.0
        with:
          REQUIRED_LABELS_ALL: "lgtm"

      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ github.token }}"
          MERGE_LABELS: "lgtm"
          MERGE_METHOD: "squash"