name: Automerge

on:
#   # Try enabling auto-merge for all open pull requests.
#   # (Only recommended for testing.)
#   push:

#   # Try enabling auto-merge for all open pull requests.
#   schedule:
#     - cron: 0 * * * *

  # Try enabling auto-merge when a pull request is approved. Note that this
  # event skips the check for the pull request author association and instead
  # checks the review author association.
#   pull_request_review:
#     types:
#       - submitted

  # Try enabling auto-merge for a pull request when a draft is marked as
  # “ready for review”, when a required label is applied or when a
  # “do not merge” label is removed, or when a pull request is updated in
  # any way (opened, synchronized, reopened, edited).
#   pull_request_target:
#     types:
#         - labeled
#         - unlabeled
#         - synchronize
#         - opened
#         - edited
#         - ready_for_review
#         - reopened
#         - unlocked

#   check_suite:
#     types:
#       - completed

  # Try enabling auto-merge for the specified pull request,
  # review or all open pull requests if none is specified.
#   workflow_dispatch:
#     inputs:
#       pull-request:
#         description: Pull Request Number
#         required: false
#       review:
#         description: Review ID
#         required: false
    

# second
    # pull_request:
    #     types:
    #     - labeled
    #     - unlabeled
    #     - synchronize
    #     - opened
    #     - edited
    #     - ready_for_review
    #     - reopened
    #     - unlocked
    # pull_request_review:
    #     types:
    #     - submitted
    # check_suite:
    #     types:
    #     - completed
    # status: {}

    workflow_run:
        workflows: ['Check Label Gates']

jobs:
  automerge:
    name: Automerge Job
    runs-on: ubuntu-latest
    
    steps:
    - id: auto-merge
      name: Merge with Target Branch
      uses: pascalgn/automerge-action@v0.16.3
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "lgtm"
          MERGE_METHOD: "squash"


    #   - id: dry-run
    #     name: Automerge Dry Run
    #     uses: reitermarkus/automerge@v2
    #     with:
    #       token: ${{ secrets.GITHUB_TOKEN }}
    #       merge-method: squash
    #       do-not-merge-labels: never-merge
    #       required-labels: lgtm
    #       pull-request: ${{ github.event.inputs.pull-request }}
    #       review: ${{ github.event.inputs.review }}
    #       dry-run: true

    #   - id: auto-merge
    #     name: Merge with Target Branch
    #     uses: reitermarkus/automerge@v2
    #     with:
    #         token: ${{ secrets.GITHUB_TOKEN }}
    #         merge-method: squash
    #         do-not-merge-labels: never-merge
    #         required-labels: lgtm
    #         pull-request: ${{ github.event.inputs.pull-request }}
    #         review: ${{ github.event.inputs.review }}
