name: build-publish-staging

on:
    push:
      branches: 
        - main 

jobs:
    build-preview:
      name: Build Staging Artifacts
      environment: 
        name: preview
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Setup NodeJS
          uses: actions/setup-node@v2
          with:
            node-version: 18 # Use Node.js 18 her

        - name: Install NodeJS Dependencies
          run: npm install
  
        - name: Build Static App
          env: 
            REACT_APP_DOCUSAURUS_BASE_URL: ${{ vars.DOCUSAURUS_BASE_URL }}
          run: npm run build
        
        - name: Get Commit Hash
          id: commit_hash
          uses: prompt/actions-commit-hash@v3

        - name: Get Current Date
          id: date
          run: echo "::set-output name=today::$(date +'%Y%m%d')"

        - name: Build Docker Metadata
          id: meta
          uses: docker/metadata-action@v5
          with:
            # list of Docker images to use as base name for tags
            images: |
              ${{ vars.REGISTRY }}/${{ vars.REGISTRY_ORG }}/docusaurus-play
            # generate Docker tags based on the following events/attributes
            tags: |
              type=raw,value=v0.1.2

        - name: Login to Container Registry
          uses: docker/login-action@v3
          with:
            registry: ${{ vars.REGISTRY }}
            username: ${{ secrets.REGISTRY_USER }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
          
        - name: Setup Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v3

        - name: Build and Push (Docker Image)
          id: docker_build 
          uses: docker/build-push-action@v2
          with: 
            context: ./
            file: ./Dockerfile
            push: ${{ github.event_name != 'pull_request' }}
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
