name: Build and Deploy Production Docker Images

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
    build-stable:
      name: Build Production Artifacts
      environment: 
        name: stable
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Setup NodeJS
          uses: actions/setup-node@v2
          with:
            node-version: 18 # Use Node.js 18 her

        - name: Install NodeJS Dependencies
          run: npm install
  
        - name: Build Static App
          env: 
            REACT_APP_DOCUSAURUS_BASE_URL: ${{ vars.DOCUSAURUS_BASE_URL }}
          run: npm run build
        
        - name: Build Docker Metadata
          id: meta
          uses: docker/metadata-action@v5
          with:
            # list of Docker images to use as base name for tags
            images: |
              ${{ vars.CONTAINER_REGISTRY_ORG }}/docusaurus-play
            # generate Docker tags based on the following events/attributes
            tags: |
              type=semver,pattern={{major}}.{{minor}}.{{patch}}
              type=raw,value=latest
    
        - name: Login to Container Registry
          uses: docker/login-action@v3
          with:
            registry: ${{ vars.CONTAINER_REGISTRY }}
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
          
        - name: Setup Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v3

        - name: Build and Push (Docker Image)
          id: docker_build 
          uses: docker/build-push-action@v2
          with: 
            context: ./
            file: ./Dockerfile
            push: ${{ github.event_name != 'pull_request' }}
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            annotations: ${{ steps.meta.outputs.annotations }}