name: Check Label Gates

on:
    pull_request:
      types: 
        - labeled 
        - unlabeled
        - opened
        - reopened
        - synchronize
        - edited
    pull_request_review:
      types:
        - submitted
    check_suite:
      types:
        - completed

jobs:
    check-release-gates:
      name: Check LGTM Gate
      runs-on: ubuntu-latest
  
      steps:
        - name: Enforce Gates
          uses: yogevbd/enforce-label-action@2.1.0
          with:
            REQUIRED_LABELS_ALL: "lgtm"