name: check-label-gates

on:
    pull_request:
      types: 
        - labeled 
        - unlabeled

jobs:
    check-release-gates:
      if: ${{ github.event.label.name == 'approve-production' }}
      name: Check Release Gates
      runs-on: ubuntu-latest
  
      steps:
        - name: Enforce Gates
          uses: yogevbd/enforce-label-action@2.1.0
          with:
            REQUIRED_LABELS_ALL: "approve-production,approve-staging"