name: Pre-flight Checks

on:
    pull_request: 
      branches:
        - main
      types:
        - opened
        - reopened
        - synchronize
        - closed

jobs:
    preflight-check:
      name: Checks 
      environment: 
        name: preview
      runs-on: ubuntu-latest
  
      steps:
        - name: Relabel Pull Request
          id: labelPr
          if: github.event.action != 'closed' 
          uses: jburgess/AddRemovePrLabels@v1.0.4
          with:
            githubToken: ${{ github.token }}
            labelsToRemove: lgtm


        - name: Checkout
          if: github.event.action != 'closed'
          uses: actions/checkout@v4
  
        - name: Setup NodeJS
          uses: actions/setup-node@v4
          if: github.event.action != 'closed' 
          with:
            node-version: 'lts/*'
            cache: npm
  
        - name: Install Dependencies
          if: github.event.action != 'closed' 
          run: npm install

        # - name: Run Linter
        #   run: | 
        #     cd src 
        #     npm run lint

        - name: Build Static App
          if: github.event.action != 'closed' 
          env: 
            REACT_APP_DOCUSAURUS_BASE_URL: ${{ vars.DOCUSAURUS_BASE_URL }}
          run: npm run build
    
        - name: Login to Container Registry
          if: github.event.action != 'closed' 
          uses: docker/login-action@v3
          with:
            registry: ${{ vars.REGISTRY }}
            username: ${{ secrets.REGISTRY_USER }}
            password: ${{ secrets.REGISTRY_PASSWORD }}

    