name: Deploy Ephemeral Pull Request Environment

on:
    pull_request: 
      branches:
        - main
      types:
        - opened
        - reopened
        - synchronize

jobs:
    preflight-check:
      name: Pre-Flight Checks 
      environment: 
        name: preview
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Setup NodeJS
          uses: actions/setup-node@v2
          with:
            node-version: 'lts/*'
            cache: yarn
  
        - name: Install Dependencies
          run: yarn install

        - name: Run Linter
          run: yarn lint
  
        - name: Build Static App
          env: 
            REACT_APP_DOCUSAURUS_BASE_URL: ${{ vars.DOCUSAURUS_BASE_URL }}
          run: yarn run build
    
        - name: Login to Container Registry
          uses: docker/login-action@v3
          with:
            registry: ${{ vars.REGISTRY }}
            username: ${{ secrets.REGISTRY_USER }}
            password: ${{ secrets.REGISTRY_PASSWORD }}

    deploy-ephemeral-preview:
      name: Deploy Ephemeral Preview 
      environment: 
        name: pull-requests-preview
        url: 'https://arch-stg.otc-service.com'
      runs-on: ubuntu-20.04
      needs: [ preflight-check ]

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install and Build
          env: 
            REACT_APP_DOCUSAURUS_BASE_URL: ${{ vars.DOCUSAURUS_BASE_URL }}pr-${{ github.event.pull_request.number }}
          run: |
            yarn install
            yarn run build

        - name: Deploy
          uses: rossjrw/pr-preview-action@v1
          with:
            source-dir: ./build/
