on:
    push:
      branches:
        - dev
      paths-ignore:
        - '**/README.md'
    
jobs:
    build-preview:
      environment: preview
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout
          uses: actions/checkout@v2
  
        - name: Setup NodeJS
          uses: actions/setup-node@v2
          with:
            node-version: 18 # Use Node.js 18 here
  
        - name: Install Dependencies
          run: npm install
  
        - name: Build App
          run: npm run build
    
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
          
        - name: Setup Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1 
        
        - name: Get Commit Hash
          id: commit_hash
          uses: prompt/actions-commit-hash@v3
        - uses: docker/setup-buildx-action@v3
        - name: Build and Push (Docker Image)
          id: docker_build 
          uses: docker/build-push-action@v2
          with: 
            context: ./
            file: ./Dockerfile
            push: true
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMG_NAME }}:${{ vars.APP_VERSION }}.${{github.run_number}}-${{ steps.commit_hash.outputs.short }}-preview
      

          
      